name = "Sandbox"
uuid = "9307e30f-c43e-9ca7-d17c-c2dc59df670d"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "1.5.1"

[deps]
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
Tar_jll = "9b64493d-8859-5bf3-93d7-7c32dd38186f"
UserNSSandbox_jll = "b88861f7-1d72-59dd-91e7-a8cc876a4984"

[compat]
Preferences = "1.2.5"
Scratch = "1"
Tar_jll = "1.34.0"
UserNSSandbox_jll = "2022.3.30"
julia = "1.6"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Downloads", "Pkg", "Test"]
